name: make

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Run Makefile
        run: make build
      - name: Stage to branch "build"
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          src_path: build
          dst_path: /.
          dst_owner: matanlurey
          dst_repo_name: mtn.lu
